#############################################################################
# Makefile for building: yuv
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 9? 28 01:18:50 2014
# Project:  yuv.pro
# Template: app
# Command: /usr/local/QtARM4.8/bin/qmake -o Makefile yuv.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/QtARM4.8/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/usr/local/QtARM4.8/include/QtCore -I/usr/local/QtARM4.8/include/QtNetwork -I/usr/local/QtARM4.8/include/QtGui -I/usr/local/QtARM4.8/include -I. -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/QtARM4.8/lib
LIBS          = $(SUBLIBS)  -L/usr/local/QtARM4.8/lib -lQtGui -L/usr/local/QtARM4.8/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /usr/local/QtARM4.8/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		yuv2rgb16tab.c \
		yuv420rgb888c.c moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		yuv2rgb16tab.o \
		yuv420rgb888c.o \
		moc_widget.o
DIST          = /usr/local/QtARM4.8/mkspecs/common/unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/linux.conf \
		/usr/local/QtARM4.8/mkspecs/common/gcc-base.conf \
		/usr/local/QtARM4.8/mkspecs/common/gcc-base-unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/g++-base.conf \
		/usr/local/QtARM4.8/mkspecs/common/g++-unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/qws.conf \
		/usr/local/QtARM4.8/mkspecs/qconfig.pri \
		/usr/local/QtARM4.8/mkspecs/features/qt_functions.prf \
		/usr/local/QtARM4.8/mkspecs/features/qt_config.prf \
		/usr/local/QtARM4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/QtARM4.8/mkspecs/features/default_pre.prf \
		/usr/local/QtARM4.8/mkspecs/features/release.prf \
		/usr/local/QtARM4.8/mkspecs/features/default_post.prf \
		/usr/local/QtARM4.8/mkspecs/features/shared.prf \
		/usr/local/QtARM4.8/mkspecs/features/warn_on.prf \
		/usr/local/QtARM4.8/mkspecs/features/qt.prf \
		/usr/local/QtARM4.8/mkspecs/features/unix/thread.prf \
		/usr/local/QtARM4.8/mkspecs/features/moc.prf \
		/usr/local/QtARM4.8/mkspecs/features/resources.prf \
		/usr/local/QtARM4.8/mkspecs/features/uic.prf \
		/usr/local/QtARM4.8/mkspecs/features/yacc.prf \
		/usr/local/QtARM4.8/mkspecs/features/lex.prf \
		/usr/local/QtARM4.8/mkspecs/features/include_source_dir.prf \
		yuv.pro
QMAKE_TARGET  = yuv
DESTDIR       = 
TARGET        = yuv

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yuv.pro  /usr/local/QtARM4.8/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /usr/local/QtARM4.8/mkspecs/common/unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/linux.conf \
		/usr/local/QtARM4.8/mkspecs/common/gcc-base.conf \
		/usr/local/QtARM4.8/mkspecs/common/gcc-base-unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/g++-base.conf \
		/usr/local/QtARM4.8/mkspecs/common/g++-unix.conf \
		/usr/local/QtARM4.8/mkspecs/common/qws.conf \
		/usr/local/QtARM4.8/mkspecs/qconfig.pri \
		/usr/local/QtARM4.8/mkspecs/features/qt_functions.prf \
		/usr/local/QtARM4.8/mkspecs/features/qt_config.prf \
		/usr/local/QtARM4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/QtARM4.8/mkspecs/features/default_pre.prf \
		/usr/local/QtARM4.8/mkspecs/features/release.prf \
		/usr/local/QtARM4.8/mkspecs/features/default_post.prf \
		/usr/local/QtARM4.8/mkspecs/features/shared.prf \
		/usr/local/QtARM4.8/mkspecs/features/warn_on.prf \
		/usr/local/QtARM4.8/mkspecs/features/qt.prf \
		/usr/local/QtARM4.8/mkspecs/features/unix/thread.prf \
		/usr/local/QtARM4.8/mkspecs/features/moc.prf \
		/usr/local/QtARM4.8/mkspecs/features/resources.prf \
		/usr/local/QtARM4.8/mkspecs/features/uic.prf \
		/usr/local/QtARM4.8/mkspecs/features/yacc.prf \
		/usr/local/QtARM4.8/mkspecs/features/lex.prf \
		/usr/local/QtARM4.8/mkspecs/features/include_source_dir.prf \
		/usr/local/QtARM4.8/lib/libQtGui.prl \
		/usr/local/QtARM4.8/lib/libQtNetwork.prl \
		/usr/local/QtARM4.8/lib/libQtCore.prl
	$(QMAKE) -o Makefile yuv.pro
/usr/local/QtARM4.8/mkspecs/common/unix.conf:
/usr/local/QtARM4.8/mkspecs/common/linux.conf:
/usr/local/QtARM4.8/mkspecs/common/gcc-base.conf:
/usr/local/QtARM4.8/mkspecs/common/gcc-base-unix.conf:
/usr/local/QtARM4.8/mkspecs/common/g++-base.conf:
/usr/local/QtARM4.8/mkspecs/common/g++-unix.conf:
/usr/local/QtARM4.8/mkspecs/common/qws.conf:
/usr/local/QtARM4.8/mkspecs/qconfig.pri:
/usr/local/QtARM4.8/mkspecs/features/qt_functions.prf:
/usr/local/QtARM4.8/mkspecs/features/qt_config.prf:
/usr/local/QtARM4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/QtARM4.8/mkspecs/features/default_pre.prf:
/usr/local/QtARM4.8/mkspecs/features/release.prf:
/usr/local/QtARM4.8/mkspecs/features/default_post.prf:
/usr/local/QtARM4.8/mkspecs/features/shared.prf:
/usr/local/QtARM4.8/mkspecs/features/warn_on.prf:
/usr/local/QtARM4.8/mkspecs/features/qt.prf:
/usr/local/QtARM4.8/mkspecs/features/unix/thread.prf:
/usr/local/QtARM4.8/mkspecs/features/moc.prf:
/usr/local/QtARM4.8/mkspecs/features/resources.prf:
/usr/local/QtARM4.8/mkspecs/features/uic.prf:
/usr/local/QtARM4.8/mkspecs/features/yacc.prf:
/usr/local/QtARM4.8/mkspecs/features/lex.prf:
/usr/local/QtARM4.8/mkspecs/features/include_source_dir.prf:
/usr/local/QtARM4.8/lib/libQtGui.prl:
/usr/local/QtARM4.8/lib/libQtNetwork.prl:
/usr/local/QtARM4.8/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile yuv.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/yuv1.0.0 || $(MKDIR) .tmp/yuv1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/yuv1.0.0/ && $(COPY_FILE) --parents widget.h yuv2rgb.h .tmp/yuv1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp yuv2rgb16tab.c yuv420rgb888c.c .tmp/yuv1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/yuv1.0.0/ && (cd `dirname .tmp/yuv1.0.0` && $(TAR) yuv1.0.0.tar yuv1.0.0 && $(COMPRESS) yuv1.0.0.tar) && $(MOVE) `dirname .tmp/yuv1.0.0`/yuv1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/yuv1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: widget.h
	/usr/local/QtARM4.8/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/local/QtARM4.8/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		ui_widget.h \
		yuv2rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

yuv2rgb16tab.o: yuv2rgb16tab.c yuv2rgb.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o yuv2rgb16tab.o yuv2rgb16tab.c

yuv420rgb888c.o: yuv420rgb888c.c yuv2rgb.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o yuv420rgb888c.o yuv420rgb888c.c

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

